---
title: "About me"
---
Stuff about me


### Current work

My current projects are listed below:
Secondary Health Effects – I am working with a team dedicated to analyzing pandemic era policy decisions at the state level and measuring their impacts on health outcomes. This project has received seed funding for the total of $10,000, and in it’s early stages is focused on health outcomes in infant and young mothers. 
Election Integrity & Public Officials Social Media – this project involves understanding how state level officials operate within the digital politics sphere. It pays special attention to how state lawmakers tweet about elections and election integrity.
Election policy diffusion – This is an on-going project that measures the diffusion of state election policy and the causal forces behind this process.
Online hate speech by state officials – This project aims to understand how lawmakers tweet about their constituents, paying close attention to the rise in hate speech and crimes towards AAPI constituents since 2020. 
 



### Hometown -- Education -- Research

I was born in Columbus Indiana, and graduated from from Colmbus East High School. I received my undergad degree from Franklin College in Franklin, Indiana in Political Science and Journalism. I received my Doctorate in political science from the University of Illinois at Chicago in 2022. I currently live in State College, PA. 
